[profile.default]
src = "src"
out = "out"
libs = ["lib"]
show_progress = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
ast = true

[invariant]
show_metrics = true
runs = 1024
depth = 1000
